### ISSUE TITLE
the sandbox has no GNOME desktop installed by default

### ISSUE THREAD

**Issue by philippeback** [abajwa-hw/vnc-stack#1]
Doing

```
yum groupinstall Desktop
```

will get the X and GNOME on the system.

About 133M download.

FWIW, this is nice too for getting into the thing.

http://www.server-world.info/en/note?os=CentOS_6&p=x&f=2

**Comment by abajwa-hw** [comment]
Thanks for your note Philipppe. Yes "yum groupinstall Desktop" is one of things executed during the install phase of the vnc-stack to install the desktop on sandbox. You can see the master.py code for full details:
https://github.com/abajwa-hw/vnc-stack/blob/master/package/scripts/master.py#L16

I have updated the README.md to include links to ultraVNC/TightVNC as other options to desktop into the sandbox. Let me know if does not answer all your questions.

**Comment by philippeback** [comment]
Ok, thanks for the pointer.

Looks like one of the first things I'll do on a sandox will be to install a vnc-stack.

And making it all work together with 

https://github.com/seanorama/ambari-bootstrap
